{
  imports = [
    ./boot.nix
    ./fonts.nix
    ./graphics.nix
    ./hardware.nix
    ./network.nix
    ./nix.nix
    ./packages.nix
    ./programs.nix
    ./services.nix
    ./users.nix
    ./virtualisation.nix
    ../ly.nix
    ../qtile.nix
    #../gdm.nix
    ../dwm.nix
  ];
}
